### ISSUE TITLE
glib2-devel dependency used without being checked or required

### ISSUE THREAD

**Issue by kalikiana** [os-autoinst/os-autoinst#2029]
`os-autoinst-devel` doesn't seem to install `glib2-devel` which is required to build *tinycv*:

    [ 58%] Building CXX object ppmclibs/CMakeFiles/tinycv.dir/tinycv_impl.cc.o                                                                                                            
    /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libgobject-2.0.so.0: undefined reference to `g_pattern_spec_copy'                                
    /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libgstreamer-1.0.so.0: undefined reference to `g_pattern_spec_match_string'

Btw the build didn't fail before either, so the `CMakeLists.txt` doesn't even seem to look for it.

**Comment by Martchus** [comment]
> Btw the build didn't fail before either, so the CMakeLists.txt doesn't even seem to look for it.

Yes, and that makes sense as we don't use glib2/gstreamer/gobject - at least not directly. They are likely pulled in by a pkgconfig file of a dependency. However, apparently in a way that's kind of broken as apparently only gstreamer/gobject are pulled in and maybe glib2 itself is missing. Run the build with `VERBOSE=1` to show the linker invocation to clarify this.

We need to find out how the dependency is pulled in. Since it is not pulled in by us directly, maybe a broken pkgconfig file in a devel package we use is the culprit. And of course the environment is important because it is likely a packaging issue (in some packages installed on your system).

**Comment by kalikiana** [comment]
> In which environment can we reproduce this?

    toolbox -u -t mytestbox
    $ zypper in -y os-autoinst-devel
    $ rm -Rf build; mkdir build; cd build; cmake ..; cd ..
    $ cmake --build build -t test-perl-testsuite TESTS="t/14-isotovideo.t"
    
This is assuming you [have rootless containers setup](https://github.com/kubic-project/microos-toolbox#podman-cant-pullrun-images-with-user). You can probably reproduce on a Tumbleweed host with a writable root filesystem if the dependencies aren't installed.

**Comment by okurz** [comment]
I can't reproduce a problem with

```
podman run --rm -it --pull=always registry.opensuse.org/opensuse/tumbleweed /bin/sh -c 'zypper -n in os-autoinst-devel && rpm -qa | grep glib2 ; zypper -n in os-autoinst-devel && rpm -qa | grep glib2; git clone --depth 1 https://github.com/os-autoinst/os-autoinst /tmp/os-autoinst && make -C /tmp/os-autoinst test-perl-testsuite VERBOSE=1 TESTS="t/14-isotovideo.t"'
```

**Comment by Martchus** [comment]
I also cannot reproduce it on my "normal" Tumbleweed system. So something must be special about your environment.

---

Not sure whether the linker invocation you've mentioned is the one responsible for the error (a bit more consecutive log lines would be nice). Nevertheless, I'd say it looks as it is supposed to look. `libglib-2.0.so.0`/`libgstreamer-1.0.so.0`/`libgobject-2.0.so.0` are pulled in by `libopencv_videoio.so.4.5.5` but since those are dynamic libs and only privately used by `libopencv_videoio.so.4.5.5` so it shouldn't be required to have `libglib-2.0.so.0` in the linker line. This also means that `glib2-devel` should *not* be required. Since `libgstreamer-1.0.so.0` and `libgobject-2.0.so.0` are installed in your system I assume that `libglib-2.0.so.0` (the library itself) is also installed as a dependency. However, maybe a wrong version of that library is installed or a wrong version of that library is picked up from another location (e.g. lingering development build). You can debug this by invoking the linker line manually and playing around with linker flags.

So I'd say our build system is producing the right linker invocation and the problem is somewhere within your environment.
