### ISSUE TITLE
QEMU emulation for s390x

### ISSUE THREAD

**Issue by srbala** [os-autoinst/os-autoinst#2246]
What is the status QEMU emulation for s390x? It appears `qemu-system-s390x` is not in the lookup list https://github.com/os-autoinst/os-autoinst/blob/master/backend/qemu.pm#L601

Can we use software emulation for `s390x` ISO testing?

**Comment by kalikiana** [comment]
[qemu supports s390x](https://wiki.qemu.org/Documentation/Platforms/S390X) via `s390-virtio-ccw`:

> The s390-virtio-ccw machine emulates a virtual channel subsystem. Currently, only virtio-ccw proxy devices

That said I've never looked into it. If you feel comfortable making a small change in that code, maybe you'd like to give it a try?

**Comment by okurz** [comment]
@srbala SUSE uses the backends https://github.com/os-autoinst/os-autoinst/blob/master/backend/svirt.pm and https://github.com/os-autoinst/os-autoinst/blob/master/backend/s390x.pm for s90x related testing so kvm on a dedicated hypervisor host and z/VM virtualization. That's why we might not have seen more issues.

**Comment by skriesch** [comment]
@okurz These contributions are from AlmaLinux and based on Red Hat KVM. It should be an expansion of possible tests.

**Comment by okurz** [comment]
@skriesch yes, I got that. How can we help more?

**Comment by Martchus** [comment]
Closing in favor https://github.com/os-autoinst/os-autoinst/issues/2312.
